apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: get-ip-app
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/${REPOSITORY_NAME}:get-ip-app"
    imagePullPolicy: Always
    volumeMounts:
    - name: shared-volume
      mountPath: /data

  - name: upload-s3-app
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/${REPOSITORY_NAME}:upload-s3-app"
    imagePullPolicy: Always
    volumeMounts:
    - name: shared-volume
      mountPath: /data

  volumes:
  - name: shared-volume
    emptyDir: {}