apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
      - name: get-ip-app
        image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}:get-ip-app"
        imagePullPolicy: Always
        command: ["sh", "-c", "while true; do python3 /usr/src/get_ip/get_ip.py; sleep 3600; done"]
        volumeMounts:
        - name: shared-volume
          mountPath: /data

      - name: upload-s3-app
        image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}:upload-s3-app"
        imagePullPolicy: Always
        command: ["/bin/sh"]
        volumeMounts:
        - name: shared-volume
          mountPath: /data
      volumes:
      - name: shared-volume
        emptyDir: {}
