name: "Build-Upload-DockerImages"
on:
  workflow_dispatch:
  push:
    # paths:
    #   - "Terraform/**"
    branches:
      - develop
  # pull_request:
  #   paths:
  #     - "DockerFiles/**"
  #   branches:
  #     - develop
  #     - release
  #     - main

env:
  image_tag: ${{ github.ref == 'refs/heads/main' && 'latest' || (github.ref == 'refs/heads/develop' && 'beta') }}

jobs:
  build-docker:
    name: "Build Docker Images"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker images
        run: |
          set -e
          for dir in DockerFiles/*; do
            if [ -d "$dir" ]; then
              image_name=$(basename "$dir")

              docker build \
                --tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:${image_name}-${env.image_tag} \
                --file "$dir/Dockerfile" \
                "$dir"
              
              docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${image_name}-${env.image_tag}
            fi
          done
