name: Deploy Kubernetes Pod

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "k8s/**"
    branches:
      - develop
      - release
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./k8s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.TF_AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.TF_AWS_SECRET_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{
            secrets.AWS_EKS_CLUSTER_NAME }}

      - name: Prepare Kubernetes Pod Manifest
        run: |
          export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          export AWS_REGION=${{ secrets.AWS_REGION }}
          export REPOSITORY_NAME=${{ secrets.REPOSITORY_NAME }}

          envsubst < ./pod/pod.yml > ./pod/pod-template.yml

      - name: Verify kubectl connection
        run: |
          kubectl get nodes

      - name: Apply Kubernetes Manifest
        run: |
          kubectl apply -f ./pod/pod-template.yml --v=7
