name: 'Deploy Infra from Terraform'

on:
  workflow_dispatch:
  pull_request:
    # paths:
    #   - "Terraform/**"
    branches:
      - develop
      - release
      - main
  push:
    # paths:
    #   - "Terraform/**"
    branches:
      - feature/**

jobs:
  apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_KEY}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')
      run: terraform validate

    - name: Terraform Plan
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'pull_request'
      run: terraform apply -auto-approve -var-file=./terraform.tfvars